[build]
  # Build command injects environment variables into the HTML
  command = "npm run netlify:inject-env"
  publish = "public"

# Headers for security (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
